#!/usr/bin/env bash

DOCKER_PROJECT_NAME="todo";
DOCKER_FOLDER_PATH="docker";
DOCKER_COMPOSE_FILE="docker-compose.yml"

POSTGRES_DB="todo_database";
POSTGRES_USER="user";
POSTGRES_PASSWORD="user_password";
POSTGRES_HOST="api_postgres";
POSTGRES_PORT="5432";

POSTGRES_TEST_DB="todo_database_test";
POSTGRES_TEST_USER="user_test";
POSTGRES_TEST_PASSWORD="todo_password_test";
POSTGRES_TEST_HOST="api_postgrestest";
POSTGRES_TEST_PORT="5432";

DOCKER_COMPOSE="
env DOCKER_PROJECT_NAME=${DOCKER_PROJECT_NAME} \
DOCKER_FOLDER_PATH=${DOCKER_FOLDER_PATH} \
POSTGRES_DB=${POSTGRES_DB} \
POSTGRES_USER=${POSTGRES_USER} \
POSTGRES_PASSWORD=${POSTGRES_PASSWORD} \
POSTGRES_TEST_DB=${POSTGRES_TEST_DB} \
POSTGRES_TEST_USER=${POSTGRES_TEST_USER} \
POSTGRES_TEST_PASSWORD=${POSTGRES_TEST_PASSWORD} \
docker compose -f ./${DOCKER_COMPOSE_FILE}";

list=(\
"help" \
"docker-check" \
"docker-phpcs" \
"docker-phpcbf" \
"docker-phpstan" \
"docker-phpunit" \
"docker-composer" \
"docker-php" \
"start" \
"stop" \
"build" \
"rebuild" \
"docker-console" \
"clear-cache" \
"clear-log" \
"clear-session" \
"clear-all" \
"make-project" \
"remove-project" \
"docker-migration" \
"docker-migrate" \
);

if [ $# -gt 0 ]; then
    if [ "$1" == "docker-check" ]; then
        shift 1
        ./develop docker-phpcs
        ./develop docker-phpstan
        ./develop docker-phpunit
    elif [ "$1" == "docker-phpcs" ]; then
        shift 1
        ${DOCKER_COMPOSE} exec api_php-fpm \
            php ./vendor/bin/phpcs -p "$@"
    elif [ "$1" == "docker-phpcbf" ]; then
        shift 1
        ${DOCKER_COMPOSE} exec api_php-fpm \
            php ./vendor/bin/phpcbf "$@"
    elif [ "$1" == "docker-phpstan" ]; then
        shift 1
        ${DOCKER_COMPOSE} exec api_php-fpm \
            php ./vendor/bin/phpstan "$@"
    elif [ "$1" == "docker-phpunit" ]; then
        shift 1
        ${DOCKER_COMPOSE} exec api_php-fpm \
            php ./vendor/bin/phpunit "$@"
    elif [ "$1" == "docker-composer" ]; then
        shift 1
        ${DOCKER_COMPOSE} exec api_php-fpm \
            composer "$@"
        chmod --silent -R 777 ./vendor
    elif [ "$1" == "docker-php" ]; then
        shift 1
        ${DOCKER_COMPOSE} exec api_php-fpm "$@"
    elif [ "$1" == "start" ]; then
        shift 1
        ${DOCKER_COMPOSE} up -d --remove-orphans
    elif [ "$1" == "stop" ]; then
        shift 1
        ${DOCKER_COMPOSE} stop
    elif [ "$1" == "build" ]; then
        shift 1
        ${DOCKER_COMPOSE} up -d --build
    elif [ "$1" == "rebuild" ]; then
        shift 1
        ${DOCKER_COMPOSE} up -d --no-deps --build "$@"
    elif [ "$1" == "docker-console" ]; then
        shift 1
        ${DOCKER_COMPOSE} exec api_php-fpm \
            ./bin/console "$@"
    elif [ "$1" == "docker-migration" ]; then
        shift 1
        ./develop docker-console make:migration
    elif [ "$1" == "docker-migrate" ]; then
        shift 1
        ./develop docker-console doctrine:migrations:migrate
    elif [ "$1" == "clear-cache" ]; then
        shift 1
        ${DOCKER_COMPOSE} exec api_php-fpm \
            rm -rf ./var/cache/*
    elif [ "$1" == "clear-log" ]; then
        shift 1
        ${DOCKER_COMPOSE} exec api_php-fpm \
            rm -rf ./var/log/*
    elif [ "$1" == "clear-session" ]; then
        shift 1
        ${DOCKER_COMPOSE} exec api_php-fpm \
            rm -rf ./var/sessions/*
    elif [ "$1" == "clear-all" ]; then
        shift 1
        ./develop clear-cache
        ./develop clear-log
        ./develop clear-session
    elif [ "$1" == "make-project" ]; then
        shift 1
        jwt=$(LC_ALL=C tr -dc 'A-Za-z0-9@#%^&*()_+=-{}[]:;<>,.?/' < /dev/urandom | head -c 32 | xargs echo)
        echo -e "\n" >> .env.local
        echo -e "APP_ENV=dev" >> .env.local
        echo -e "DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?serverVersion=17&charset=utf8" >> .env.local
        echo -e "JWT_PASSPHRASE="${jwt} >> .env.local
        echo -e "\n" >> .env.test.local
        echo -e "APP_ENV=test" >> .env.test.local
        echo -e "DATABASE_URL=postgresql://${POSTGRES_TEST_USER}:${POSTGRES_TEST_PASSWORD}@${POSTGRES_TEST_HOST}:${POSTGRES_TEST_PORT}/${POSTGRES_TEST_DB}?serverVersion=17&charset=utf8" >> .env.test.local
        echo -e "JWT_PASSPHRASE="${jwt} >> .env.test.local
        echo -e "KERNEL_CLASS='App\Kernel'" >> .env.test.local
        echo -e "APP_SECRET='$ecretf0rt3st'" >> .env.test.local
        ./develop start
        ./develop docker-composer install --optimize-autoloader
        ./develop docker-console lexik:jwt:generate-keypair
        ./develop docker-console --env=test doctrine:schema:create
    elif [ "$1" == "remove-project" ]; then
        shift 1
        ./develop docker-php rm ./.env.local
        ./develop docker-php rm ./.env.test.local
        ./develop docker-php rm ./config/jwt/private.pem
        ./develop docker-php rm ./config/jwt/public.pem
        ./develop stop
        docker rm $(docker ps -a --format '{{.ID}}' --filter name=${DOCKER_PROJECT_NAME})
        docker volume rm $(docker volume ls --filter name=${DOCKER_PROJECT_NAME} --format '{{.Name}}')
        docker image rm -f $(docker images --filter=reference="${DOCKER_PROJECT_NAME}*" --format '{{.ID}}')
        docker network rm $(docker network ls --filter name=${DOCKER_PROJECT_NAME} --format '{{.Name}}')
    elif [ "$1" == "help" ]; then
        shift 1
        for i in ${list[@]}
          do
            echo $i
          done
    else
        echo "./develop: Unknown command '$@'"
    fi
else
    echo "./develop: You must specify some command"
fi
