version: '3'
services:
  api_nginx:
    container_name: "${DOCKER_PROJECT_NAME}_nginx"
    build: ./${DOCKER_FOLDER_PATH}/nginx/
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/project/current
      - ./${DOCKER_FOLDER_PATH}/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - api_php-fpm
    networks:
      - internal
  api_php-fpm:
    container_name: "${DOCKER_PROJECT_NAME}_php-fpm"
    build:
      context: .
      dockerfile: ./${DOCKER_FOLDER_PATH}/php-fpm/Dockerfile
    volumes:
      - .:/var/www/project/current/
      - ./${DOCKER_FOLDER_PATH}/php-fpm/conf.d/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./${DOCKER_FOLDER_PATH}/php-fpm/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    environment:
      PHP_EXTENSION_XDEBUG: ${PHP_EXTENSION_XDEBUG:-false}
    extra_hosts:
      host.docker.internal: host-gateway
    networks:
      - internal
  api_postgres:
    container_name: "${DOCKER_PROJECT_NAME}_postgres"
    build: ./${DOCKER_FOLDER_PATH}/postgres/
    ports:
      - 5445:5432
    shm_size: 1g
    volumes:
      - postgres_volume:/var/lib/postgresql/data
      - ./${DOCKER_FOLDER_PATH}/postgres/conf.d/:/etc/postgresql/
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    command:
      - "postgres"
      - "-c"
      - "config_file=/etc/postgresql/postgresql.conf"
    networks:
      - internal
  api_postgrestest:
    container_name: "${DOCKER_PROJECT_NAME}_postgrestest"
    build: ./${DOCKER_FOLDER_PATH}/postgrestest/
    volumes:
      - postgrestest_volume:/var/lib/postgresql/data
      - ./${DOCKER_FOLDER_PATH}/postgres/instructions:/usr/src
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_TEST_PASSWORD}
      POSTGRES_USER: ${POSTGRES_TEST_USER}
      POSTGRES_DB: ${POSTGRES_TEST_DB}
    networks:
      - internal
  api_pgadmin:
    container_name: "${DOCKER_PROJECT_NAME}_pgadmin"
    build: ./${DOCKER_FOLDER_PATH}/pgadmin/
    volumes:
      - pgadmin_volume:/var/lib/pgadmin
    ports:
      - 8081:80
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: password
    networks:
      - internal
  api_redis:
    container_name: "${DOCKER_PROJECT_NAME}_redis"
    build: ./${DOCKER_FOLDER_PATH}/redis/
    networks:
      - internal
  api_rediscommander:
    container_name: "${DOCKER_PROJECT_NAME}_rediscommander"
    build: ./${DOCKER_FOLDER_PATH}/rediscommander/
    ports:
      - 8083:8081
    environment:
      - REDIS_HOSTS=local:api_redis:6379
    networks:
      - internal
volumes:
  postgres_volume:
    driver: local
  postgrestest_volume:
    driver: local
  pgadmin_volume:
    driver: local
networks:
  internal:
    external: true
