### Login Check Success
POST http://localhost:8080/api/token
Content-Type: application/json

{
    "username": "test@test.com",
    "password": "123456"
}

### Login Check Fail
POST http://localhost:8080/api/token
Content-Type: application/json

{
    "username": "test",
    "password": "123"
}

